### ISSUE TITLE
Can i use scipy instead of pynio engine in xarray

### ISSUE THREAD

**Issue by Jayayadav33** [NCAR/pynio#56]
I am trying to read a hdf5 file. But there is an error for the line:
**data = xr.open_dataset(filename, engine='pynio')**
Error:- **ValueError: unrecognized engine pynio must be one of: ['netcdf4', 'scipy', 'rasterio', 'store']**
I am using windows 11 and unable to install pynio in anaconda. Can i use scipy instead of pynio in the above command??

**Comment by kafitzgerald** [comment]
I'd look into h5py which should work on Windows.  

This [FAQ in the xarray docs](https://docs.xarray.dev/en/stable/getting-started-guide/faq.html#how-do-i-open-format-x-file-as-an-xarray-dataset
) might be a good starting point.

**Comment by Jayayadav33** [comment]
If the files are .hdf then what engine to use??

**Comment by kafitzgerald** [comment]
The xarray FAQ linked above has info on what backends/engines will work for various file types (including HDF5).  The link should take you directly to that portion of the FAQ, but you may need to search a bit if not.    

If you have further usage questions regarding xarray, I'd suggest posting in the xarray [GitHub Discussions](https://github.com/pydata/xarray/discussions).

Closing since this is more of an xarray question.
